### ISSUE TITLE
mss.exception.ScreenShotError: gdi32.GetDIBits() failed.

### ISSUE THREAD

**Issue by HametAk** [alpharaoh/AmongUsBot#6]
after starting discord bot and then start.py there is this error...

[*] A chrome window will open now...
[*] Enter your discord credentials in the window before we start

DevTools listening on ws://127.0.0.1:53447/devtools/browser/35ab0198-2b48-4cd5-9c3d-adb7a79e4a12
[22048:17340:0912/201838.403:ERROR:device_event_log_impl.cc(208)] [20:18:38.402] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.

[*] Starting engine...
[*] This may take a moment...

Ready.
You can play now.

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Hamet\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Hamet\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Hamet\Desktop\AmongUsBot-master\start.py", line 24, in grabDiscussionTitle
    module_grabscreen.grabDiscussionTitle(self.x, self.y)
  File "C:\Users\Hamet\Desktop\AmongUsBot-master\modules\module_grabscreen.py", line 26, in grabDiscussionTitle
    sct_img = sct.grab(settings)
  File "C:\Users\Hamet\AppData\Local\Programs\Python\Python38\lib\site-packages\mss\base.py", line 88, in grab
    return self._grab_impl(monitor)
  File "C:\Users\Hamet\AppData\Local\Programs\Python\Python38\lib\site-packages\mss\windows.py", line 296, in _grab_impl
    raise ScreenShotError("gdi32.GetDIBits() failed.")
mss.exception.ScreenShotError: gdi32.GetDIBits() failed.

**Comment by alpharaoh** [comment]
New update has fixed this problem
